### ISSUE TITLE
 place-converter change

### ISSUE THREAD

**Issue by dayjournal** [aws-geospatial/amazon-location-utilities-datatypes-js#28]
### Describe the bug

With the current implementation, when using MapLibre GL JS map.on('click'), the nested object becomes a string.

1. Using JSON.parse
const place = JSON.parse(e.features![0].properties.Place);
const description = place.Label;

2. Eliminate nesting of GeoJSON properties as much as possible
const description = e.features![0].properties['Place.Label'];

I suggest eliminating the nesting of GeoJSON properties as much as possible.

### Expected Behavior

Expected Output

`{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "id": "xxxxx",
            "properties": {
                "Categories": [
                    "PointOfInterestType",
                    "Train Station",
                    "Tourist Attraction"
                ],
                "Country": "JPN",
                "Interpolated": false,
                "Label": "〒100-0005 東京都千代田区丸の内1丁目9 東京駅",
                "Municipality": "千代田区",
                "PostalCode": "100-0005",
                "Region": "東京都",
                "SupplementalCategories": [
                    "Landmark-Attraction",
                    "Historical Monument",
                    "Underground Train-Subway",
                    "Public Transit Access"
                ],
                "TimeZone": {
                    "Name": "Asia/Tokyo",
                    "Offset": 32400
                }
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    139.76729,
                    35.68096
                ]
            }
        }
    ]
}`

### Current Behavior

With the current implementation, when using MapLibre GL JS map.on('click'), the nested object becomes a string.

`[
    {
        "geometry": {
            "type": "Point",
            "coordinates": [
                139.7672939300537,
                35.680951698616454
            ]
        },
        "type": "Feature",
        "properties": {
            "Distance": 26.597834034556257,
            "Place": "{\"Categories\":[\"PointOfInterestType\",\"Train Station\",\"Tourist Attraction\"],\"Country\":\"JPN\",\"Interpolated\":false,\"Label\":\"〒100-0005 東京都千代田区丸の内1丁目9 東京駅\",\"Municipality\":\"千代田区\",\"PostalCode\":\"100-0005\",\"Region\":\"東京都\",\"SupplementalCategories\":[\"Landmark-Attraction\",\"Historical Monument\",\"Underground Train-Subway\",\"Public Transit Access\"],\"TimeZone\":{\"Name\":\"Asia/Tokyo\",\"Offset\":32400}}"
        },
        "layer": {
            "id": "search-result",
            "type": "circle",
            "source": "search-result",
            "paint": {
                "circle-color": {
                    "r": 1,
                    "g": 0,
                    "b": 0,
                    "a": 1
                },
                "circle-radius": 10
            },
            "layout": {}
        },
        "source": "search-result",
        "state": {}
    }
]`

`{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "id": "xxxxx",
            "properties": {
                "Distance": 26.597834034556257,
                "Place": {
                    "Categories": [
                        "PointOfInterestType",
                        "Train Station",
                        "Tourist Attraction"
                    ],
                    "Country": "JPN",
                    "Interpolated": false,
                    "Label": "〒100-0005 東京都千代田区丸の内1丁目9 東京駅",
                    "Municipality": "千代田区",
                    "PostalCode": "100-0005",
                    "Region": "東京都",
                    "SupplementalCategories": [
                        "Landmark-Attraction",
                        "Historical Monument",
                        "Underground Train-Subway",
                        "Public Transit Access"
                    ],
                    "TimeZone": {
                        "Name": "Asia/Tokyo",
                        "Offset": 32400
                    }
                }
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    139.76729,
                    35.68096
                ]
            }
        }
    ]
}`

### Reproduction Steps

`map.on('click', 'search-result', (e) => {
        console.log(e.features);
});`

### Possible Solution

Added "flattenProperties" to flatten GeoJSON properties.
https://github.com/aws-geospatial/amazon-location-utilities-datatypes-js/pull/29

### Environment details (OS name and version, browser, etc.)

All environments are covered

**Comment by dayjournal** [comment]
Hi, @thehoneymad, @eashuang, @imraymondlee, @hy9be
Is it possible to check my issue?

**Comment by thehoneymad** [comment]
@dayjournal thank you for reaching out. This should be addressed.

**Comment by eashuang** [comment]
Thanks for reaching out @dayjournal. Can you elaborate a bit more on the issue, like
1. Can you show us the code on how convertPlaceToFeature is used with MapLibre?
2. Can I have a sample input and output of convertPlaceToFeature causing the issue?

**Comment by dayjournal** [comment]
Hi, @eashuang 
Details are provided below.

> Can you show us the code on how convertPlaceToFeature is used with MapLibre?

`
import './style.css'
import 'maplibre-gl/dist/maplibre-gl.css';
import maplibregl from 'maplibre-gl';
import { LocationClient, SearchPlaceIndexForTextCommand } from "@aws-sdk/client-location";
import { placeToFeatureCollection } from '@aws/amazon-location-utilities-datatypes';
import { withAPIKey } from '@aws/amazon-location-utilities-auth-helper';

const region = import.meta.env.VITE_REGION;
const mapApiKey = import.meta.env.VITE_MAP_API_KEY;
const mapName = import.meta.env.VITE_MAP_NAME;
const placeApiKey = import.meta.env.VITE_PLACE_API_KEY;
const placeName = import.meta.env.VITE_PLACE_NAME;

const authHelper = await withAPIKey(placeApiKey);

const client = new LocationClient({
    region: region,
    ...authHelper.getLocationClientConfig()
});
const input = {
    IndexName: placeName,
    Text: "東京",
};
const command = new SearchPlaceIndexForTextCommand(input);
const response = await client.send(command);
const featureCollection = placeToFeatureCollection(response);

const map = new maplibregl.Map({
    container: 'map',
    style: `https://maps.geo.${region}.amazonaws.com/maps/v0/maps/${mapName}/style-descriptor?key=${mapApiKey}`,
    center: [139.767, 35.681],
    zoom: 11,
});

map.addControl(
    new maplibregl.NavigationControl({
        visualizePitch: true,
    })
);

map.on('load', function () {
    map.addSource("search-result", {
        type: "geojson",
        data: featureCollection
    });
    map.addLayer({
        'id': "search-result",
        'type': 'circle',
        'source': 'search-result',
        'layout': {},
        'paint': {
            'circle-color': '#007cbf',
            'circle-radius': 10
        }
    });
    map.on('click', 'search-result', (e) => {
        const coordinates = e.lngLat;
        const description = e.features![0].properties.Place.Label;
        new maplibregl.Popup()
            .setLngLat(coordinates)
            .setHTML(description)
            .addTo(map);
    });
    map.on('mouseenter', 'search-result', () => {
        map.getCanvas().style.cursor = 'pointer';
    });
    map.on('mouseleave', 'search-result', () => {
        map.getCanvas().style.cursor = '';
    });
});
`

> Can I have a sample input and output of convertPlaceToFeature causing the issue?

input

`
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "id": "xxxxx",
            "properties": {
                "Place": {
                    "Categories": [
                        "RegionType"
                    ],
                    "Country": "JPN",
                    "Interpolated": false,
                    "Label": "東京都",
                    "Region": "東京都",
                    "TimeZone": {
                        "Name": "Asia/Tokyo",
                        "Offset": 32400
                    }
                }
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    139.75371,
                    35.69393
                ]
            }
        }
    ]
}
`

output (When "map.on('click')" is used)

`
[
    {
        "geometry": {
            "type": "Point",
            "coordinates": [
                139.7537112236023,
                35.693935682002376
            ]
        },
        "type": "Feature",
        "properties": {
            "Place": "{\"Categories\":[\"RegionType\"],\"Country\":\"JPN\",\"Interpolated\":false,\"Label\":\"東京都\",\"Region\":\"東京都\",\"TimeZone\":{\"Name\":\"Asia/Tokyo\",\"Offset\":32400}}"
        },
        "layer": {
            "id": "search-result",
            "type": "circle",
            "source": "search-result",
            "paint": {
                "circle-color": {
                    "r": 0,
                    "g": 0.48627450980392156,
                    "b": 0.7490196078431373,
                    "a": 1
                },
                "circle-radius": 10
            },
            "layout": {}
        },
        "source": "search-result",
        "state": {}
    }
]
`

**Comment by eashuang** [comment]
Thanks for the details! Yes I think it will benefit if we could support flattening the properties. I left a comment on your PR, please have a look when you have time.

**Comment by dayjournal** [comment]
Hi, @eashuang 
Updated code.
