### ISSUE TITLE
route-converter change

### ISSUE THREAD

**Issue by dayjournal** [aws-geospatial/amazon-location-utilities-datatypes-js#33]
### Describe the bug

With the current implementation, when using MapLibre GL JS map.on('click'), the nested object becomes a string.

### Expected Behavior

`{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "DataSource": "Here",
                "Distance": 6.157,
                "DistanceUnit": "Kilometers",
                "DurationSeconds": 597
            },
            "bbox": [
                139.7466015,
                35.664799,
                139.775649,
                35.702796
            ],
            "geometry": {
                "type": "MultiLineString",
                "coordinates": [
                    [
                        [
                            139.746602,
                            35.664799
                        ],
                        [
                            139.775649,
                            35.702796
                        ]
                    ]
                ]
            }
        }
    ]
}`

### Current Behavior

With the current implementation, when using MapLibre GL JS map.on('click'), the nested object becomes a string.

`[
    {
        "geometry": {
            "type": "LineString",
            "coordinates": [
                [
                    139.74660873413086,
                    35.66479283857099
                ],
                [
                    139.77564096450806,
                    35.70278797825108
                ]
            ]
        },
        "type": "Feature",
        "properties": {
            "Summary": "{\"DataSource\":\"Here\",\"Distance\":6.157,\"DistanceUnit\":\"Kilometers\",\"DurationSeconds\":597}"
        },
        "layer": {
            "id": "route-result",
            "type": "line",
            "source": "route-result",
            "layout": {
                "line-join": "round",
                "line-cap": "round"
            },
            "paint": {
                "line-color": {
                    "r": 1,
                    "g": 0,
                    "b": 0,
                    "a": 1
                },
                "line-width": 10,
                "line-opacity": 0.5
            }
        },
        "source": "route-result",
        "state": {}
    }
]`

### Reproduction Steps

`map.on('click', 'route-result', (e) => {
        console.log(e.features);
});`

### Possible Solution

Added "flattenProperties" to flatten GeoJSON properties.
https://github.com/aws-geospatial/amazon-location-utilities-datatypes-js/pull/34

### Environment details (OS name and version, browser, etc.)

All environments are covered

**Comment by eashuang** [comment]
Thanks @dayjournal, just reviewed your PR. Since we will have 2 places with similar flattenProperties function after your proposed PR. Is it possible to combine them and extract them to a standalone file?

**Comment by juaneslucero** [comment]
Hi @dayjournal , my teammate @eashuang reviewed your PR and left some comments. We would be able merge it once the comments are addressed.

**Comment by dayjournal** [comment]
Hi, @eashuang, @juaneslucero 
Changed pull requests to the latest.

**Comment by dayjournal** [comment]
Hi, @eashuang, @juaneslucero
Can you check my pull request? And update npm to the latest version. 
I will write an article when this is updated.

**Comment by imraymondlee** [comment]
Hi @dayjournal, npm has been updated with the latest version. Thank you for your contribution.
